version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_DETAILS=mongodb://mongodb:27017

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/dbc

  ollama:
    build:
      context: ./ollama
    ports:
      - "11434:11434"  # Example port, update as necessary
    stdin_open: true  # equivalent to -i
    tty: true        # equivalent to -t
  
  
  





volumes:
  mongo-data: